input.onButtonPressed(Button.A, function () {
    Heh.move(-1)
})
input.onButtonPressed(Button.B, function () {
    Heh.move(1)
})
let Object_2: game.LedSprite = null
let Object1: game.LedSprite = null
let Heh: game.LedSprite = null
basic.showNumber(3)
basic.pause(100)
basic.showNumber(2)
basic.pause(100)
basic.showNumber(1)
basic.pause(100)
basic.showString("Go")
basic.pause(300)
Heh = game.createSprite(2, 3)
game.setLife(3)
game.setScore(1)
basic.pause(300)
for (let index = 0; index < 10; index++) {
    Object1 = game.createSprite(randint(0, 4), 0)
    Object1.turn(Direction.Right, 90)
    basic.pause(500)
    Object1.move(1)
    basic.pause(500)
    Object1.move(1)
    basic.pause(500)
    Object1.move(1)
    basic.pause(500)
    Object1.move(1)
    basic.pause(500)
    Object1.delete()
}
for (let index = 0; index < 15; index++) {
    Object1 = game.createSprite(randint(0, 4), 0)
    Object1.turn(Direction.Right, 90)
    basic.pause(400)
    Object1.move(1)
    basic.pause(400)
    Object1.move(1)
    basic.pause(400)
    Object1.move(1)
    basic.pause(400)
    Object1.move(1)
    basic.pause(400)
    Object1.delete()
}
for (let index = 0; index < 20; index++) {
    Object1 = game.createSprite(randint(0, 4), 0)
    Object1.turn(Direction.Right, 90)
    basic.pause(200)
    Object1.move(1)
    basic.pause(200)
    Object1.move(1)
    basic.pause(200)
    Object1.move(1)
    basic.pause(200)
    Object1.move(1)
    basic.pause(200)
    Object1.delete()
}
for (let index = 0; index < 20; index++) {
    Object1 = game.createSprite(randint(0, 4), 0)
    Object_2 = game.createSprite(randint(0, 4), 0)
    Object1.turn(Direction.Right, 90)
    Object_2.turn(Direction.Right, 90)
    basic.pause(200)
    Object1.move(1)
    Object_2.move(1)
    basic.pause(200)
    Object1.move(1)
    Object_2.move(1)
    basic.pause(200)
    Object1.move(1)
    Object_2.move(1)
    basic.pause(200)
    Object1.move(1)
    Object_2.move(1)
    basic.pause(200)
    Object1.delete()
    Object_2.delete()
}
basic.forever(function () {
    if (Heh.isTouching(Object1)) {
        game.removeLife(1)
    }
})
